apiVersion: v1
kind: Service
metadata:
  name: nginx-sa
  labels:
    app: nginx-sa
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: webapp-619657
    tier: frontend
  type: NodePort
